<a href="https://colab.research.google.com/github/Tonainings/BigDataProject_Poliba/blob/main/ProjectPOLIBA_RegressioneMultipla.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df= pd.read_csv("_student_prediction.csv")


#x_train = np.array(df["CUML_GPA"])   #una variabile da 145 valori
#y_train = np.array(df["GRADE"])

print(df.info())

#X = np.array([df["PREP_STUDY"],df["PREP_EXAM"],df["NOTES"],df["LISTENS"]])       # 4 variabili da 145 valori per ognuno
#Y = np.array(df["GRADE"])
#W = np.array([-4.0, 1.0, 1.0, 1.0])
#b = 0


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   STUDENTID      145 non-null    object
 1   AGE            145 non-null    int64 
 2   GENDER         145 non-null    int64 
 3   HS_TYPE        145 non-null    int64 
 4   SCHOLARSHIP    145 non-null    int64 
 5   WORK           145 non-null    int64 
 6   ACTIVITY       145 non-null    int64 
 7   PARTNER        145 non-null    int64 
 8   SALARY         145 non-null    int64 
 9   TRANSPORT      145 non-null    int64 
 10  LIVING         145 non-null    int64 
 11  MOTHER_EDU     145 non-null    int64 
 12  FATHER_EDU     145 non-null    int64 
 13  #_SIBLINGS     145 non-null    int64 
 14  KIDS           145 non-null    int64 
 15  MOTHER_JOB     145 non-null    int64 
 16  FATHER_JOB     145 non-null    int64 
 17  STUDY_HRS      145 non-null    int64 
 18  READ_FREQ      145 non-null   

In [ ]:
#df.sort_values(by=['GRADE'], ascending= TRUE, implace= TRUE)                     #sort by

df.head(10)  #mostra i primi 10 record


STUDENTID  AGE  GENDER  HS_TYPE  SCHOLARSHIP  WORK  ACTIVITY  PARTNER  \
0   STUDENT1    2       2        3            3     1         2        2   
1   STUDENT2    2       2        3            3     1         2        2   
2   STUDENT3    2       2        2            3     2         2        2   
3   STUDENT4    1       1        1            3     1         2        1   
4   STUDENT5    2       2        1            3     2         2        1   
5   STUDENT6    2       2        2            3     2         2        2   
6   STUDENT7    1       2        2            4     2         2        2   
7   STUDENT8    1       1        2            3     1         1        1   
8   STUDENT9    2       1        3            3     2         1        1   
9  STUDENT10    2       1        2            3     2         2        1   

   SALARY  TRANSPORT  ...  PREP_STUDY  PREP_EXAM  NOTES  LISTENS  \
0       1          1  ...           1          1      3        2   
1       1          1  ...           1          1      3        2   
2       2          4  ...           1          1      2        2   
3       2          1  ...           1          2      3        2   
4       3          1  ...           2          1      2        2   
5       2          1  ...           1          1      1        2   
6       1          1  ...           1          1      3        3   
7       2          2  ...           3          1      3        2   
8       1          1  ...           1          1      3        2   
9       3          4  ...           1          1      2        2   

   LIKES_DISCUSS  CLASSROOM  CUML_GPA  EXP_GPA  COURSE ID  GRADE  
0              1          2         1        1          1      1  
1              3          2         2        3          1      1  
2              1          1         2        2          1      1  
3              2          1         3        2          1      1  
4              2          1         2        2          1      1  
5              1          2         4        4          1      2  
6              3          3         4        4          1      5  
7              2          1         1        1          1      2  
8              2          2         4        3          1      5  
9              2          2         1        2          1      0  

[10 rows x 33 columns]

In [ ]:

X1 = df[['PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
#X2 = np.array(X1, dtype=float)
#X = X2.transpose()                                                                 #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
Y = np.array(Y1, dtype=float)
#Y2 = np.array(Y1, dtype=float)
#Y = Y2.transpose()

W = np.array([-4.0, 1.0, 1.0, 1.0])
b = 0

print(X)
print(Y)
print(W)

print(type(X))                                                                      #stampa il tipo di variabile
print(X.dtype)                                                                      #stampa il formato dei valori di una variabile
print(type(Y))
print(Y.dtype)
print(type(W))
print(W.dtype)

#x_train = np.array(df["CUML_GPA"])   #una variabile da 145 valori
#y_train = np.array(df["GRADE"])

#X = np.array([df["PREP_STUDY"],df["PREP_EXAM"],df["NOTES"],df["LISTENS"]])       # 4 variabili da 145 valori per ognuno
#Y = np.array(df["GRADE"])

#W = np.array([-4.0, 1.0, 1.0, 1.0])
#b = 0

#print(x_train)
#print(y_train)


[[1. 1. 3. 2.]
 [1. 1. 3. 2.]
 [1. 1. 2. 2.]
 [1. 2. 3. 2.]
 [2. 1. 2. 2.]
 [1. 1. 1. 2.]
 [1. 1. 3. 3.]
 [3. 1. 3. 2.]
 [1. 1. 3. 2.]
 [1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 2. 3. 1.]
 [1. 1. 2. 2.]
 [1. 1. 3. 2.]
 [1. 1. 2. 3.]
 [1. 1. 3. 2.]
 [1. 1. 3. 2.]
 [1. 1. 2. 2.]
 [1. 1. 3. 1.]
 [1. 1. 3. 2.]
 [1. 2. 3. 1.]
 [1. 1. 3. 1.]
 [1. 2. 3. 1.]
 [1. 1. 3. 2.]
 [1. 1. 2. 1.]
 [1. 1. 2. 1.]
 [1. 1. 3. 3.]
 [1. 1. 3. 1.]
 [1. 1. 3. 2.]
 [1. 1. 3. 2.]
 [2. 1. 2. 3.]
 [1. 1. 3. 3.]
 [1. 1. 2. 2.]
 [1. 1. 1. 3.]
 [1. 1. 2. 2.]
 [1. 1. 2. 1.]
 [2. 1. 2. 1.]
 [1. 1. 3. 2.]
 [2. 1. 2. 2.]
 [1. 1. 2. 2.]
 [1. 1. 3. 1.]
 [1. 1. 3. 2.]
 [1. 1. 2. 1.]
 [1. 1. 3. 1.]
 [2. 1. 3. 2.]
 [1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [1. 1. 2. 1.]
 [1. 1. 3. 2.]
 [2. 1. 2. 2.]
 [1. 1. 2. 2.]
 [1. 1. 2. 3.]
 [1. 2. 2. 2.]
 [1. 1. 2. 2.]
 [1. 2. 3. 1.]
 [3. 3. 1. 3.]
 [1. 2. 3. 2.]
 [1. 1. 3. 2.]
 [1. 1. 3. 2.]
 [1. 1. 3. 3.]
 [1. 1. 1. 3.]
 [1. 1. 3. 2.]
 [1. 1. 2. 3.]
 [3. 1. 2. 2.]
 [2. 1. 3. 2.]
 [2. 1. 2. 1.]
 [1. 1. 3.

In [ ]:
import numpy as np

def compute_multiple_cost(X, Y, W, b):                                                    # creazione di una funzione "compute cost"

  m = X.shape[0];                                                              # dichiaro che la variabile m è uguale alla dimensione degli elementi di x

  cost = 0                                                                       # dichiaro che la variabile cost (la sola sommatoria della cost_function) sia uguale a 0
  for i in range(m):
    X_i = X[i,:]
    f_Wb = np.dot(W,X_i) + b                                                          # ciclo for, con i = 1 : m (i che varia da 1 a m) RICORDA: m è la dimensione degli elementi di x!!
    #f_wb = w*x[i] + b
    err_i = f_Wb - Y[i]                                                           # x(i) ,, f_wb è la funzione di una generica retta
    cost = cost + (err_i)**2                                               # incrementa il valore di cost con la somma del valore di cost della precedente iterazione e di ciò che è tra parentesi, dove:
                                                                                 #f_wb è la retta presa in considerazione e y[i] è la distanza (altezza) del punto con la retta.
                                                                                 #cost è stato incrementato, seguirà una nuova iterazione.
    total_cost = (1/(2*m))*cost                                                    # concluso il ciclo for, total_cost sarà la cost_function completa
  return total_cost                                                              # return chiude la funzione compute_cost e mi conserva la variabile locale total_cost per il resto del codice. Rendendola globale



total_cost = compute_multiple_cost(X,Y,W,b)

print(total_cost)

[9.37241379]


In [ ]:
import numpy as np
def compute_multiple_gradient(X, Y, W, b):



  m = X.shape[0]                                                                  #ha specificato una cosa al riguardo per le iterazioni sulle righe ma operando sulle colonne per il modo di programmazione
                                                                                  # m number of traininge samples (examples)
  n = X.shape[1]                                                                  # n number of feature classes
  dj_dW = np.zeros(n)
  dj_db = 0
  print(m)
  print(n)
  for i in range(m):
    X_i = X[i,:]                                                                  #posso mettere questa associazione fuori dal secondo ciclo for perchè non dipende da J
    f_xi = np.dot(W,X_i) + b                                                      #prediction
    err_i = f_xi-Y[i]                                                             #error = prediction - ground-truth
    for j in range(n):

      #f_xi = w*x[i]+b
      #f_xi = np.dot(w,x[i]) + b
      #X_i = X[i,:]     #lasciarlo qui comporta un calcolo computazionale evitabile
      #f_xi = np.dot(W,X_i) + b

      x_ji = X[i,j]
      print('f_xi = {}'.format(f_xi));
      print('Y[i] = {}'.format(Y[i]));

      #dj_dW[j] = dj_dW[j] + (1/m)*x_ji*(f_xi-y[i]);

      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i;
      print('dj_dW[j] = {}'.format(dj_dW[j]))

      #dj_dW = np.append(dj_dW, dj_dwj)

    dj_db = dj_db + (1/m) * err_i;

    #for i in range(m):
      #dot_product = np.dot(W,X[:,1])
      #dj_db = dj_db + (1/m) * (dot_product + b - y[i]);

  return dj_dW, dj_db

#X = np.array([[1.0, 0.0], [2.0, -2.0],[5.0 , 3.0], [4.0, -1.0]])
#y = np.array([7, 6, 36, 19])
#W = np.array([5,3])
#b = 2





dj_dW,  dj_db = compute_multiple_gradient(X, Y,  W,  b)
print(dj_dW,dj_db)

145
4
f_xi = 2.0
Y[i] = [1.]
dj_dW[j] = 0.006896551724137931
f_xi = 2.0
Y[i] = [1.]
dj_dW[j] = 0.006896551724137931
f_xi = 2.0
Y[i] = [1.]
dj_dW[j] = 0.020689655172413793
f_xi = 2.0
Y[i] = [1.]
dj_dW[j] = 0.013793103448275862
f_xi = 2.0
Y[i] = [1.]
dj_dW[j] = 0.013793103448275862
f_xi = 2.0
Y[i] = [1.]
dj_dW[j] = 0.013793103448275862
f_xi = 2.0
Y[i] = [1.]
dj_dW[j] = 0.041379310344827586
f_xi = 2.0
Y[i] = [1.]
dj_dW[j] = 0.027586206896551724
f_xi = 1.0
Y[i] = [1.]
dj_dW[j] = 0.013793103448275862
f_xi = 1.0
Y[i] = [1.]
dj_dW[j] = 0.013793103448275862
f_xi = 1.0
Y[i] = [1.]
dj_dW[j] = 0.041379310344827586
f_xi = 1.0
Y[i] = [1.]
dj_dW[j] = 0.027586206896551724
f_xi = 3.0
Y[i] = [1.]
dj_dW[j] = 0.027586206896551724
f_xi = 3.0
Y[i] = [1.]
dj_dW[j] = 0.041379310344827586
f_xi = 3.0
Y[i] = [1.]
dj_dW[j] = 0.08275862068965517
f_xi = 3.0
Y[i] = [1.]
dj_dW[j] = 0.05517241379310345
f_xi = -3.0
Y[i] = [1.]
dj_dW[j] = -0.027586206896551724
f_xi = -3.0
Y[i] = [1.]
dj_dW[j] = 0.013793103448275862
f_x

# Sample

In [ ]:
import numpy as np
def compute_multiple_gradient(X, y, W, b):



  m = X.shape[0]                                                                  #ha specificato una cosa al riguardo per le iterazioni sulle righe ma operando sulle colonne per il modo di programmazione
                                                                                  # m number of traininge samples (examples)
  n = X.shape[1]                                                                  # n number of feature classes
  dj_dW = np.zeros(n)
  dj_db = 0
  print(m)
  print(n)
  for i in range(m):
    X_i = X[i,:]                                                                  #posso mettere questa associazione fuori dal secondo ciclo for perchè non dipende da J
    f_xi = np.dot(W,X_i) + b                                                      #prediction
    err_i = f_xi-y[i]                                                             #error = prediction - ground-truth
    for j in range(n):

      #f_xi = w*x[i]+b
      #f_xi = np.dot(w,x[i]) + b
      #X_i = X[i,:]     #lasciarlo qui comporta un calcolo computazionale evitabile
      #f_xi = np.dot(W,X_i) + b

      x_ji = X[i,j]
      print('f_xi = {}'.format(f_xi));
      print('y[i] = {}'.format(y[i]));

      #dj_dW[j] = dj_dW[j] + (1/m)*x_ji*(f_xi-y[i]);

      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i;
      print('dj_dW[j] = {}'.format(dj_dW[j]))

      #dj_dW = np.append(dj_dW, dj_dwj)

    dj_db = dj_db + (1/m) * err_i;

    #for i in range(m):
      #dot_product = np.dot(W,X[:,1])
      #dj_db = dj_db + (1/m) * (dot_product + b - y[i]);

  return dj_dW, dj_db

#X = np.array([[1.0, 0.0], [2.0, -2.0],[5.0 , 3.0], [4.0, -1.0]])
#y = np.array([7, 6, 36, 19])
#W = np.array([5,3])
#b = 2





dj_dW,  dj_db = compute_multiple_gradient(X, y,  W,  b)
print(dj_dW,dj_db)

# Continua

In [ ]:
def multiple_gradient_descent(X, Y,  w_in, b_in, alpha,  num_iters,  compute_multiple_cost, compute_multiple_gradient):

  W = w_in
  b = b_in

  for itt in range(num_iters):
    dj_dw, dj_db = compute_multiple_gradient(X, Y, W, b)
    W = W - alpha*dj_dw
    b = b - alpha*dj_db
    cost = compute_multiple_cost(X, Y, W, b)
    if itt % 100 == 0:
      print('Itteration {}:, (W,b) = ({},{}, cost = {}'.format(itt, W, b, cost))
  #return w, b, cost      perchè funziona comunque? oss: ci mette 1 secondo in più
  return W, b, cost

#x_train = np.array([1.0, 2.0, 5.0, 4.0])
#y_train = np.array([1.0, 2.0, 5.0, 4.0])

w_in = np.array([-4.0, 1.0, 1.0, 1.0])
#W_in = np.array([0.01, 0.01, 0.01, 0.01])
b_in = 2
#w_in = 0.1
#b_in = 0.1
alpha = 0.01
num_itt = 100
multiple_gradient_descent(X, Y, w_in, b_in, alpha, num_itt, compute_multiple_cost, compute_multiple_gradient)

Output streaming troncato alle ultime 5000 righe.
dj_dW[j] = 0.5572974114880559
f_xi = [3.47826199]
y[i] = [2.]
dj_dW[j] = 0.4617195698723945
f_xi = [4.31596797]
y[i] = [3.]
dj_dW[j] = 0.1721150156261377
f_xi = [4.31596797]
y[i] = [3.]
dj_dW[j] = 0.25685050839575896
f_xi = [4.31596797]
y[i] = [3.]
dj_dW[j] = 0.5845243350103834
f_xi = [4.31596797]
y[i] = [3.]
dj_dW[j] = 0.4798708522206128
f_xi = [4.62671794]
y[i] = [1.]
dj_dW[j] = 0.19712686346512948
f_xi = [4.62671794]
y[i] = [1.]
dj_dW[j] = 0.30687420407374244
f_xi = [4.62671794]
y[i] = [1.]
dj_dW[j] = 0.6595598785273586
f_xi = [4.62671794]
y[i] = [1.]
dj_dW[j] = 0.5048827000596046
f_xi = [3.47826199]
y[i] = [1.]
dj_dW[j] = 0.21421832547447045
f_xi = [3.47826199]
y[i] = [1.]
dj_dW[j] = 0.3239656660830834
f_xi = [3.47826199]
y[i] = [1.]
dj_dW[j] = 0.7108342645553816
f_xi = [3.47826199]
y[i] = [1.]
dj_dW[j] = 0.5219741620689455
f_xi = [4.62671794]
y[i] = [3.]
dj_dW[j] = 0.22543706986518636
f_xi = [4.62671794]
y[i] = [3.]
dj_dW[j] = 0.34

(array([-2.77699399,  1.14978908,  0.74870801,  0.8307714 ]),
 array([2.02143369]),
 array([3.79563871]))

# Sample

In [ ]:
def multiple_gradient_descent(X, Y,  w_in, b_in, alpha,  num_iters,  compute_multiple_cost, compute_multiple_gradient):

  W = w_in
  b = b_in

  for itt in range(num_iters):
    dj_dw, dj_db = compute_multiple_gradient(X, Y, W, b)
    W = W - alpha*dj_dw
    b = b - alpha*dj_db
    cost = compute_multiple_cost(X, Y, W, b)
    if itt % 100 == 0:
      print('Itteration {}:, (W,b) = ({},{}, cost = {}'.format(itt, W, b, cost))
  #return w, b, cost      perchè funziona comunque? oss: ci mette 1 secondo in più
  return W, b, cost

#x_train = np.array([1.0, 2.0, 5.0, 4.0])
#y_train = np.array([1.0, 2.0, 5.0, 4.0])
X = np.array([[1.0, 0.0, 3.0, -1.0], [2.0, -2.0, 3.0, -2.0],[5.0 , 3.0, -1.0, 2.0], [1.0, 1.0, 1.0, -1.0]])
Y = np.array([7.0, 7.0, 7.0, 6.0])
W_in = np.array([0.01, 0.01, 0.01, 0.01])
b_in = 2
#w_in = 0.1
#b_in = 0.1
alpha = 0.01
num_itt = 100
multiple_gradient_descent(X, Y, W_in, b_in, alpha, num_itt, compute_multiple_cost, compute_multiple_gradient)

4
f_xi = 2.03
y[i] = 7.0
dj_dW[j] = -1.2425000000000002
f_xi = 2.03
y[i] = 7.0
dj_dW[j] = 0.0
f_xi = 2.03
y[i] = 7.0
dj_dW[j] = -3.7275000000000005
f_xi = 2.03
y[i] = 7.0
dj_dW[j] = 1.2425000000000002
f_xi = 2.01
y[i] = 7.0
dj_dW[j] = -3.7375000000000003
f_xi = 2.01
y[i] = 7.0
dj_dW[j] = 2.495
f_xi = 2.01
y[i] = 7.0
dj_dW[j] = -7.470000000000001
f_xi = 2.01
y[i] = 7.0
dj_dW[j] = 3.7375000000000003
f_xi = 2.09
y[i] = 7.0
dj_dW[j] = -9.875
f_xi = 2.09
y[i] = 7.0
dj_dW[j] = -1.1875
f_xi = 2.09
y[i] = 7.0
dj_dW[j] = -6.242500000000001
f_xi = 2.09
y[i] = 7.0
dj_dW[j] = 1.2825000000000002
f_xi = 2.02
y[i] = 6.0
dj_dW[j] = -10.87
f_xi = 2.02
y[i] = 6.0
dj_dW[j] = -2.1825
f_xi = 2.02
y[i] = 6.0
dj_dW[j] = -7.237500000000001
f_xi = 2.02
y[i] = 6.0
dj_dW[j] = 2.2775000000000003
Itteration 0:, (W,b) = ([ 0.1187    0.031825  0.082375 -0.012775],2.047125, cost = 9.261033631093749
4
f_xi = 2.425725
y[i] = 7.0
dj_dW[j] = -1.14356875
f_xi = 2.425725
y[i] = 7.0
dj_dW[j] = 0.0
f_xi = 2.425725
y[i] = 7.0

(array([ 0.98141584,  0.45128433,  0.95054844, -0.40086801]),
 2.609624535561346,
 0.06381454235683075)