<a href="https://colab.research.google.com/github/Tonainings/BigDataProject_Poliba/blob/main/ProjectPOLIBA_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd

In [18]:
df= pd.read_csv("_student_prediction.csv")


#x_train = np.array(df["CUML_GPA"])   #una variabile da 145 valori
#y_train = np.array(df["GRADE"])

print(df.info())

#X = np.array([df["PREP_STUDY"],df["PREP_EXAM"],df["NOTES"],df["LISTENS"]])       # 4 variabili da 145 valori per ognuno
#Y = np.array(df["GRADE"])
#W = np.array([-4.0, 1.0, 1.0, 1.0])
#b = 0


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   STUDENTID      145 non-null    object
 1   AGE            145 non-null    int64 
 2   GENDER         145 non-null    int64 
 3   HS_TYPE        145 non-null    int64 
 4   SCHOLARSHIP    145 non-null    int64 
 5   WORK           145 non-null    int64 
 6   ACTIVITY       145 non-null    int64 
 7   PARTNER        145 non-null    int64 
 8   SALARY         145 non-null    int64 
 9   TRANSPORT      145 non-null    int64 
 10  LIVING         145 non-null    int64 
 11  MOTHER_EDU     145 non-null    int64 
 12  FATHER_EDU     145 non-null    int64 
 13  #_SIBLINGS     145 non-null    int64 
 14  KIDS           145 non-null    int64 
 15  MOTHER_JOB     145 non-null    int64 
 16  FATHER_JOB     145 non-null    int64 
 17  STUDY_HRS      145 non-null    int64 
 18  READ_FREQ      145 non-null   

In [ ]:
#df.sort_values(by=['GRADE'], ascending= TRUE, implace= TRUE)                     #sort by

df.head(10)  #mostra i primi 10 record


In [38]:

#X1 = df[['PREP_STUDY']].to_numpy()
X1 = df[['PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
#X2 = np.array(X1, dtype=float)
#X = X2.transpose()                                                                 #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
y = np.array(Y1, dtype=float)
#Y2 = np.array(Y1, dtype=float)
#Y = Y2.transpose()

W = np.array([-4.0, 1.0, 1.0, 1.0])
b = 0

#print(X)
#print(y)
#print(W)

#print(type(X))                                                                      #stampa il tipo di variabile
#print(X.dtype)                                                                      #stampa il formato dei valori di una variabile
#print(type(y))
#print(y.dtype)
#print(type(W))
#print(W.dtype)

#x_train = np.array(df["CUML_GPA"])   #una variabile da 145 valori
#y_train = np.array(df["GRADE"])

#X = np.array([df["PREP_STUDY"],df["PREP_EXAM"],df["NOTES"],df["LISTENS"]])       # 4 variabili da 145 valori per ognuno
#Y = np.array(df["GRADE"])

#W = np.array([-4.0, 1.0, 1.0, 1.0])
#b = 0

#print(x_train)
#print(y_train)


Cost compute

In [41]:
#import numpy as np
def sig(x):
 return 1/(1 + np.exp(-x))

def compute_multiple_cost(X, y, W, b):

  m = X.shape[0]
  cost = 0

  for i in range(m):
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i)
    cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
  total_cost = (1/(2*m))*cost
  return total_cost

total_cost = compute_multiple_cost(X, y, W, b)



print ('for b={}, total_cost={}'.format(b,total_cost))

for b=0, total_cost=[-0.02334572]


Gradient compute

In [48]:
def compute_multiple_gradient(X, y, W, b):

  m = X.shape[0] # Number of training samples
  n = X.shape[1] # Number of feature classes

  dj_dW = np.zeros(n)
  dj_db = 0

  for i in range(m): # For each sample
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i) # Prediction
    err_i = f_xi - y[i] # Prediction - Ground truth
    for j in range(n): # For each feature
      x_ji = X[i,j]
      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i
    dj_db = dj_db + (1/m)*err_i
  return dj_dW, dj_db

dj_dW, dj_db = compute_multiple_gradient(X, y, W, b)
print(dj_dW, dj_db)

[-3.68126628 -3.10743215 -6.61884156 -5.42787515] [-2.59764199]


Gradient descent

In [60]:
def multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters,  cost_function, gradient_function):

  W = W_in
  b = b_in

  for itt in range(num_iters):
    dj_dw, dj_db = compute_multiple_gradient(X, y, W, b)
    W = W - alpha*dj_dw
    b = b - alpha*dj_db
    cost = compute_multiple_cost(X, y, W, b)

    if itt % 100 == 0:
      print('Iteration {}: (w,b) = ({}, {}), cost = {}'.format(itt, W, b, cost))

  return W, b, cost

W_in = np.array([-4.0, 1.0, 1.0, 1.0])
b_in = 1

alpha = 0.0002
num_iters = 5000

multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters, compute_multiple_cost, compute_multiple_gradient)

Iteration 0: (w,b) = ([-3.99928935  1.00059873  1.00127409  1.0010464 ], [1.00049939]), cost = [-1.30512187]
Iteration 100: (w,b) = ([-3.92913246  1.05977719  1.12717547  1.10446488], [1.04984733]), cost = [-2.24020143]
Iteration 200: (w,b) = ([-3.86067452  1.11774168  1.2504752   1.20574745], [1.09817301]), cost = [-3.13621092]
Iteration 300: (w,b) = ([-3.79370917  1.17472548  1.37173209  1.30531977], [1.14568361]), cost = [-4.00132743]
Iteration 400: (w,b) = ([-3.72801743  1.23093456  1.49143279  1.40356984], [1.19255541]), cost = [-4.8426152]
Iteration 500: (w,b) = ([-3.66345984  1.2865014   1.60990134  1.50077517], [1.23890767]), cost = [-5.6647686]
Iteration 600: (w,b) = ([-3.59995505  1.34150287  1.72733058  1.5971252 ], [1.2848159]), cost = [-6.47070097]
Iteration 700: (w,b) = ([-3.53739806  1.39601357  1.84388333  1.69278377], [1.33034666]), cost = [-7.2629984]
Iteration 800: (w,b) = ([-3.47562742  1.45012749  1.95974635  1.78791305], [1.37557431]), cost = [-8.04456006]
Iterati

<ipython-input-41-1f8d74f25a7b>:13: RuntimeWarning: divide by zero encountered in log
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)


Iteration 3800: (w,b) = ([-1.67265934  3.04883643  5.39638122  4.61165519], [2.71329214]), cost = [-inf]
Iteration 3900: (w,b) = ([-1.61265934  3.10207781  5.51086398  4.70572416], [2.75784386]), cost = [-inf]
Iteration 4000: (w,b) = ([-1.55265934  3.15531919  5.62534674  4.79979313], [2.80239559]), cost = [-inf]
Iteration 4100: (w,b) = ([-1.49265934  3.20856057  5.7398295   4.89386209], [2.84694731]), cost = [-inf]


<ipython-input-41-1f8d74f25a7b>:13: RuntimeWarning: invalid value encountered in multiply
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)


Iteration 4200: (w,b) = ([-1.43265934  3.26180195  5.85431226  4.98793106], [2.89149904]), cost = [nan]
Iteration 4300: (w,b) = ([-1.37265934  3.31504333  5.96879502  5.08200002], [2.93605076]), cost = [nan]
Iteration 4400: (w,b) = ([-1.31265934  3.3682847   6.08327778  5.17606899], [2.98060249]), cost = [nan]
Iteration 4500: (w,b) = ([-1.25265934  3.42152608  6.19776053  5.27013795], [3.02515421]), cost = [nan]
Iteration 4600: (w,b) = ([-1.19265934  3.47476746  6.31224329  5.36420692], [3.06970593]), cost = [nan]
Iteration 4700: (w,b) = ([-1.13265934  3.52800884  6.42672605  5.45827588], [3.11425766]), cost = [nan]
Iteration 4800: (w,b) = ([-1.07265934  3.58125022  6.54120881  5.55234485], [3.15880938]), cost = [nan]
Iteration 4900: (w,b) = ([-1.01265934  3.6344916   6.65569157  5.64641382], [3.20336111]), cost = [nan]


(array([-0.95325934,  3.68720057,  6.7690295 ,  5.73954209]),
 array([3.24746731]),
 array([nan]))