<a href="https://colab.research.google.com/github/Tonainings/BigDataProject_Poliba/blob/main/ProjectPOLIBA_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [4]:
df= pd.read_csv("_student_prediction.csv")


#x_train = np.array(df["CUML_GPA"])   #una variabile da 145 valori
#y_train = np.array(df["GRADE"])

print(df.info())

#X = np.array([df["PREP_STUDY"],df["PREP_EXAM"],df["NOTES"],df["LISTENS"]])       # 4 variabili da 145 valori per ognuno
#Y = np.array(df["GRADE"])
#W = np.array([-4.0, 1.0, 1.0, 1.0])
#b = 0


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   STUDENTID      145 non-null    object
 1   AGE            145 non-null    int64 
 2   GENDER         145 non-null    int64 
 3   HS_TYPE        145 non-null    int64 
 4   SCHOLARSHIP    145 non-null    int64 
 5   WORK           145 non-null    int64 
 6   ACTIVITY       145 non-null    int64 
 7   PARTNER        145 non-null    int64 
 8   SALARY         145 non-null    int64 
 9   TRANSPORT      145 non-null    int64 
 10  LIVING         145 non-null    int64 
 11  MOTHER_EDU     145 non-null    int64 
 12  FATHER_EDU     145 non-null    int64 
 13  #_SIBLINGS     145 non-null    int64 
 14  KIDS           145 non-null    int64 
 15  MOTHER_JOB     145 non-null    int64 
 16  FATHER_JOB     145 non-null    int64 
 17  STUDY_HRS      145 non-null    int64 
 18  READ_FREQ      145 non-null   

In [ ]:
#df.sort_values(by=['GRADE'], ascending= TRUE, implace= TRUE)                     #sort by

df.head(10)  #mostra i primi 10 record


In [21]:
from sklearn.preprocessing import normalize

#X1 = df[['PREP_STUDY']].to_numpy()
X1 = df[['PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X2 = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
#X2 = np.array(X1, dtype=float)
#X = X2.transpose()                                                                 #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
y = np.array(Y1, dtype=float)
#Y2 = np.array(Y1, dtype=float)
#Y = Y2.transpose()




X = normalize(X2, norm='l2')                                              #https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html#sklearn.preprocessing.normalize
                                                                                      #l1 for each non-zeros, norm. indipendent
                                                                                      #l2 for each non-zeros, norm. for feature
W = np.array([-4.0, 1.0, 1.0, 1.0])
b = 0

#print(X)
#print(y)




In [7]:
"""from sklearn.preprocessing import normalize
#X1 = df[['PREP_STUDY']].to_numpy()
X1 = df[['PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
#X2 = np.array(X1, dtype=float)
#X = X2.transpose()                                                                 #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
y = np.array(Y1, dtype=float)
#Y2 = np.array(Y1, dtype=float)
#Y = Y2.transpose()



#print(X)
#print(y)
#print(W)

#print(type(X))                                                                      #stampa il tipo di variabile
#print(X.dtype)                                                                      #stampa il formato dei valori di una variabile
#print(type(y))
#print(y.dtype)
#print(type(W))
#print(W.dtype)

#x_train = np.array(df["CUML_GPA"])   #una variabile da 145 valori
#y_train = np.array(df["GRADE"])

#X = np.array([df["PREP_STUDY"],df["PREP_EXAM"],df["NOTES"],df["LISTENS"]])       # 4 variabili da 145 valori per ognuno
#Y = np.array(df["GRADE"])

#W = np.array([-4.0, 1.0, 1.0, 1.0])
#b = 0

#print(x_train)
#print(y_train)


Cost compute

In [22]:
#import numpy as np
def sig(x):
 return 1/(1 + np.exp(-x))

def compute_multiple_cost(X, y, W, b):

  m = X.shape[0]
  cost = 0

  for i in range(m):
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i)
    cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
  total_cost = (1/(2*m))*cost
  return total_cost

total_cost = compute_multiple_cost(X, y, W, b)



print ('for b={}, total_cost={}'.format(b,total_cost))

for b=0, total_cost=[0.17489831]


Gradient compute

In [23]:
def compute_multiple_gradient(X, y, W, b):

  m = X.shape[0] # Number of training samples
  n = X.shape[1] # Number of feature classes

  dj_dW = np.zeros(n)
  dj_db = 0

  for i in range(m): # For each sample
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i) # Prediction
    err_i = f_xi - y[i] # Prediction - Ground truth
    for j in range(n): # For each feature
      x_ji = X[i,j]
      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i
    dj_db = dj_db + (1/m)*err_i
  return dj_dW, dj_db

dj_dW, dj_db = compute_multiple_gradient(X, y, W, b)
print(dj_dW, dj_db)

[-0.93610664 -0.82421162 -1.77976468 -1.44039099] [-2.69448269]


Gradient descent

In [27]:
def multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters,  cost_function, gradient_function):

  W = W_in
  b = b_in

  for itt in range(num_iters):
    dj_dw, dj_db = compute_multiple_gradient(X, y, W, b)
    W = W - alpha*dj_dw
    b = b - alpha*dj_db
    cost = compute_multiple_cost(X, y, W, b)

    if itt % 100 == 0:
      print('Iteration {}: (w,b) = ({}, {}), cost = {}'.format(itt, W, b, cost))

  return W, b, cost

W_in = np.array([-4.0, 1.0, 1.0, 1.0])
b_in = 1

alpha = 0.002
num_iters = 5000

multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters, compute_multiple_cost, compute_multiple_gradient)

Iteration 0: (w,b) = ([-3.99844095  1.00139438  1.00301704  1.00244798], [3.00455804]), cost = [-3.48983195]
Iteration 100: (w,b) = ([-3.84397293  1.13983071  1.30267502  1.24561893], [3.45709131]), cost = [-4.4816287]
Iteration 200: (w,b) = ([-3.69126841  1.27705526  1.59987889  1.48683923], [3.90567732]), cost = [-5.45634377]
Iteration 300: (w,b) = ([-3.53935972  1.41374181  1.89600586  1.72720341], [4.35251699]), cost = [-6.42356048]
Iteration 400: (w,b) = ([-3.3877999   1.55019456  2.19166893  1.96719864], [4.79860019]), cost = [-7.38754124]
Iteration 500: (w,b) = ([-3.23639092  1.68654671  2.48713388  2.20703622], [5.24435894]), cost = [-8.35013668]
Iteration 600: (w,b) = ([-3.08504678  1.82285578  2.78251453  2.44680667], [5.68997912]), cost = [-9.31214113]
Iteration 700: (w,b) = ([-2.93373043  1.95914643  3.07785936  2.68654858], [6.13554022]), cost = [-10.27389382]
Iteration 800: (w,b) = ([-2.78242599  2.0954292   3.37318899  2.92627837], [6.58107616]), cost = [-11.23553929]
It

<ipython-input-22-1f8d74f25a7b>:13: RuntimeWarning: divide by zero encountered in log
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
<ipython-input-22-1f8d74f25a7b>:13: RuntimeWarning: invalid value encountered in multiply
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)


Iteration 3900: (w,b) = ([ 1.90774184  6.32001731 12.52806759 10.35763048], [20.39212454]), cost = [nan]
Iteration 4000: (w,b) = ([ 2.05903736  6.4562942  12.82338598 10.59735131], [20.83764178]), cost = [nan]
Iteration 4100: (w,b) = ([ 2.21033288  6.5925711  13.11870438 10.83707213], [21.28315902]), cost = [nan]
Iteration 4200: (w,b) = ([ 2.3616284   6.72884799 13.41402278 11.07679295], [21.72867626]), cost = [nan]
Iteration 4300: (w,b) = ([ 2.51292392  6.86512488 13.70934117 11.31651377], [22.1741935]), cost = [nan]
Iteration 4400: (w,b) = ([ 2.66421944  7.00140178 14.00465957 11.55623459], [22.61971074]), cost = [nan]
Iteration 4500: (w,b) = ([ 2.81551496  7.13767867 14.29997797 11.79595542], [23.06522799]), cost = [nan]
Iteration 4600: (w,b) = ([ 2.96681048  7.27395556 14.59529637 12.03567624], [23.51074523]), cost = [nan]
Iteration 4700: (w,b) = ([ 3.118106    7.41023246 14.89061476 12.27539706], [23.95626247]), cost = [nan]
Iteration 4800: (w,b) = ([ 3.26940153  7.54650935 15.185

(array([ 3.57047961,  7.81770037, 15.77361677, 12.99216232]),
 array([25.28835902]),
 array([nan]))