<a href="https://colab.research.google.com/github/Tonainings/BigDataProject_Poliba/blob/main/Regu1_ProjectPOLIBA_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [9]:
df= pd.read_csv("_student_prediction.csv")


#x_train = np.array(df["CUML_GPA"])   #una variabile da 145 valori
#y_train = np.array(df["GRADE"])


#X = np.array([df["PREP_STUDY"],df["PREP_EXAM"],df["NOTES"],df["LISTENS"]])       # 4 variabili da 145 valori per ognuno
#Y = np.array(df["GRADE"])
#W = np.array([-4.0, 1.0, 1.0, 1.0])
#b = 0


In [10]:
#df.sort_values(by=['GRADE'], ascending= TRUE, implace= TRUE)                     #sort by

df.head(10)  #mostra i primi 10 record


STUDENTID  AGE  GENDER  HS_TYPE  SCHOLARSHIP  WORK  ACTIVITY  PARTNER  \
0   STUDENT1    2       2        3            3     1         2        2   
1   STUDENT2    2       2        3            3     1         2        2   
2   STUDENT3    2       2        2            3     2         2        2   
3   STUDENT4    1       1        1            3     1         2        1   
4   STUDENT5    2       2        1            3     2         2        1   
5   STUDENT6    2       2        2            3     2         2        2   
6   STUDENT7    1       2        2            4     2         2        2   
7   STUDENT8    1       1        2            3     1         1        1   
8   STUDENT9    2       1        3            3     2         1        1   
9  STUDENT10    2       1        2            3     2         2        1   

   SALARY  TRANSPORT  ...  PREP_STUDY  PREP_EXAM  NOTES  LISTENS  \
0       1          1  ...           1          1      3        2   
1       1          1  ...           1          1      3        2   
2       2          4  ...           1          1      2        2   
3       2          1  ...           1          2      3        2   
4       3          1  ...           2          1      2        2   
5       2          1  ...           1          1      1        2   
6       1          1  ...           1          1      3        3   
7       2          2  ...           3          1      3        2   
8       1          1  ...           1          1      3        2   
9       3          4  ...           1          1      2        2   

   LIKES_DISCUSS  CLASSROOM  CUML_GPA  EXP_GPA  COURSE ID  GRADE  
0              1          2         1        1          1      1  
1              3          2         2        3          1      1  
2              1          1         2        2          1      1  
3              2          1         3        2          1      1  
4              2          1         2        2          1      1  
5              1          2         4        4          1      2  
6              3          3         4        4          1      5  
7              2          1         1        1          1      2  
8              2          2         4        3          1      5  
9              2          2         1        2          1      0  

[10 rows x 33 columns]

In [ ]:
print()

In [18]:
from sklearn.preprocessing import normalize

#X1 = df[['PREP_STUDY']].to_numpy()
X1 = df[['PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X2 = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
#X2 = np.array(X1, dtype=float)
#X = X2.transpose()                                                                 #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
y2 = np.array(Y1, dtype=float)
#Y2 = np.array(Y1, dtype=float)
#Y = Y2.transpose()




#X = normalize(X2, norm='l2')                                              #https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html#sklearn.preprocessing.normalize
                                                                                      #l1 for each non-zeros, norm. indipendent
                                                                                      #l2 for each non-zeros, norm. for feature
W = np.array([-4.0, 1.0, 1.0, 1.0])
b = 0

#print(X)
#print(y)






In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 10))                                      # regularization

X = scaler.fit_transform(X2)

#print(X)

scaler = MinMaxScaler(feature_range=(0, 30))

y = scaler.fit_transform(y2)

#print(y)



In [ ]:
"""from sklearn.preprocessing import normalize
#X1 = df[['PREP_STUDY']].to_numpy()
X1 = df[['PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
#X2 = np.array(X1, dtype=float)
#X = X2.transpose()                                                                 #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
y = np.array(Y1, dtype=float)
#Y2 = np.array(Y1, dtype=float)
#Y = Y2.transpose()



#print(X)
#print(y)
#print(W)

#print(type(X))                                                                      #stampa il tipo di variabile
#print(X.dtype)                                                                      #stampa il formato dei valori di una variabile
#print(type(y))
#print(y.dtype)
#print(type(W))
#print(W.dtype)

#x_train = np.array(df["CUML_GPA"])   #una variabile da 145 valori
#y_train = np.array(df["GRADE"])

#X = np.array([df["PREP_STUDY"],df["PREP_EXAM"],df["NOTES"],df["LISTENS"]])       # 4 variabili da 145 valori per ognuno
#Y = np.array(df["GRADE"])

#W = np.array([-4.0, 1.0, 1.0, 1.0])
#b = 0

#print(x_train)
#print(y_train)


Cost compute

In [25]:
#import numpy as np
def sig(x):
 return 1/(1 + np.exp(-x))

def compute_multiple_cost(X, y, W, b):

  m = X.shape[0]
  cost = 0

  for i in range(m):
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i)
    cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
  total_cost = (1/(2*m))*cost
  return total_cost

total_cost = compute_multiple_cost(X, y, W, b)



print ('for b={}, total_cost={}'.format(b,total_cost))

for b=0, total_cost=[-45.64036196]


Gradient compute

In [26]:
def compute_multiple_gradient(X, y, W, b):

  m = X.shape[0] # Number of training samples
  n = X.shape[1] # Number of feature classes

  dj_dW = np.zeros(n)
  dj_db = 0

  for i in range(m): # For each sample
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i) # Prediction
    err_i = f_xi - y[i] # Prediction - Ground truth
    for j in range(n): # For each feature
      x_ji = X[i,j]
      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i
    dj_db = dj_db + (1/m)*err_i
  return dj_dW, dj_db

dj_dW, dj_db = compute_multiple_gradient(X, y, W, b)
print(dj_dW, dj_db)

[ -23.65285354  -12.3228894  -101.9928216   -71.61079053] [-13.06691161]


Gradient descent

In [32]:
def multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters,  cost_function, gradient_function):

  W = W_in
  b = b_in

  for itt in range(num_iters):
    dj_dw, dj_db = compute_multiple_gradient(X, y, W, b)
    W = W - alpha*dj_dw
    b = b - alpha*dj_db
    cost = compute_multiple_cost(X, y, W, b)

    if itt % 100 == 0:
      print('Iteration {}: (w,b) = ({}, {}), cost = {}'.format(itt, W, b, cost))

  return W, b, cost

W_in = np.array([1.0, 3.0, 4.0, 4.0])
b_in = 4

alpha = 0.000005
num_iters = 500

multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters, compute_multiple_cost, compute_multiple_gradient)

<ipython-input-25-1f8d74f25a7b>:13: RuntimeWarning: divide by zero encountered in log
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
<ipython-input-25-1f8d74f25a7b>:13: RuntimeWarning: invalid value encountered in add
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)


Iteration 0: (w,b) = ([1.00011052 3.00006015 4.00050153 4.00035195], [4.00006416]), cost = [nan]
Iteration 100: (w,b) = ([1.01116224 3.00607493 4.05065424 4.03554653], [4.00648042]), cost = [nan]
Iteration 200: (w,b) = ([1.02221397 3.0120897  4.10080695 4.07074111], [4.01289668]), cost = [nan]
Iteration 300: (w,b) = ([1.0332657  3.01810448 4.15095966 4.10593569], [4.01931293]), cost = [nan]
Iteration 400: (w,b) = ([1.04431742 3.02411926 4.20111236 4.14113027], [4.02572919]), cost = [nan]


(array([1.05525863, 3.03007389, 4.25076355, 4.17597291]),
 array([4.03208128]),
 array([nan]))