<a href="https://colab.research.google.com/github/Tonainings/BigDataProject_Poliba/blob/main/ULTI_To_Run_MultiLinReg_LamdaRegularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
import math, copy
import matplotlib.pyplot as plt
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import MinMaxScaler
import random
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import seaborn as sns

  # Set Dataset from GitHub

url = 'https://raw.githubusercontent.com/Tonainings/BigDataProject_Poliba/main/_student_prediction.csv'
df = pd.read_csv(url)

#df.head(10)


  #Preprocessing

X1 = df[['AGE', 'GENDER', 'HS_TYPE', 'SCHOLARSHIP', 'WORK', 'ACTIVITY', 'PARTNER', 'SALARY', 'TRANSPORT', 'LIVING', 'MOTHER_EDU', 'FATHER_EDU', '#_SIBLINGS', 'KIDS', 'MOTHER_JOB', 'FATHER_JOB', 'STUDY_HRS', 'READ_FREQ', 'READ_FREQ_SCI', 'ATTEND_DEPT', 'IMPACT', 'ATTEND', 'PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS', 'LIKES_DISCUSS', 'CLASSROOM', 'CUML_GPA', 'EXP_GPA']].to_numpy()                 #converte dataframe in array


Y1 = df[['GRADE']].to_numpy()

X2 = np.array(X1, dtype=float)
Y2 = np.array(Y1, dtype=float)

#print(X2)
#print(Y2)
#print(X2.shape)
#print(Y2.shape)

'''
    # Centralization

media_colonna_1 = np.mean(X2[:, 0])
media_colonna_2 = np.mean(X2[:, 1])
media_colonna_3 = np.mean(X2[:, 2])
media_colonna_4 = np.mean(X2[:, 3])
media_colonna_5 = np.mean(X2[:, 4])
media_colonna_6 = np.mean(X2[:, 5])
media_colonna_7 = np.mean(X2[:, 6])
media_colonna_8 = np.mean(X2[:, 7])
media_colonna_9 = np.mean(X2[:, 8])
media_colonna_10 = np.mean(X2[:, 9])
media_colonna_11 = np.mean(X2[:, 10])
media_colonna_12 = np.mean(X2[:, 11])
media_colonna_13 = np.mean(X2[:, 12])
media_colonna_14 = np.mean(X2[:, 13])
media_colonna_15 = np.mean(X2[:, 14])
media_colonna_16 = np.mean(X2[:, 15])
media_colonna_17 = np.mean(X2[:, 16])
media_colonna_18 = np.mean(X2[:, 17])
media_colonna_19 = np.mean(X2[:, 18])
media_colonna_20 = np.mean(X2[:, 19])
media_colonna_21 = np.mean(X2[:, 20])
media_colonna_22 = np.mean(X2[:, 21])
media_colonna_23 = np.mean(X2[:, 22])
media_colonna_24 = np.mean(X2[:, 23])
media_colonna_25 = np.mean(X2[:, 24])
media_colonna_26 = np.mean(X2[:, 25])
media_colonna_27 = np.mean(X2[:, 26])
media_colonna_28 = np.mean(X2[:, 27])
media_colonna_29 = np.mean(X2[:, 28])
media_colonna_30 = np.mean(X2[:, 29])

media_vettore_Y2 = np.mean(Y2[:, 0])

X = X2 - np.array([media_colonna_1, media_colonna_2, media_colonna_3, media_colonna_4, media_colonna_5, media_colonna_6, media_colonna_7, media_colonna_8, media_colonna_9, media_colonna_10, media_colonna_11, media_colonna_12, media_colonna_13, media_colonna_14, media_colonna_15, media_colonna_16, media_colonna_17, media_colonna_18, media_colonna_19, media_colonna_20, media_colonna_21, media_colonna_22, media_colonna_23, media_colonna_24, media_colonna_25, media_colonna_26, media_colonna_27, media_colonna_28, media_colonna_29, media_colonna_30,]).T
Y = Y2 -np.array([media_vettore_Y2])

print(X)

    # MinMaxScaler Regularization

scaler = MinMaxScaler(feature_range=(0, 5))
X = scaler.fit_transform(X2)
scaler = MinMaxScaler(feature_range=(0, 5))
Y1 = scaler.fit_transform(Y2)
Y = np.ravel(Y1)

print(X)
print(Y)

'''



X_tmp=X
Y_tmp=Y

  # Compute cost with Regularization Lamda

def compute_cost_linear_reg(X, Y, W, b, lamda_):

 m = X.shape[0]
 n = len(W)
 cost = 0
 for i in range(m):
 #X_i = x[i,:]
  X = X_tmp[i,:]
  f_wb_xi = np.dot(W,X) + b

  cost = cost / (2*m)

  reg_cost = 0
  for j in range(n):
    reg_cost += (W[j]**2)
    reg_cost = (lamda_/(2*m)) * reg_cost

    total_cost = cost + reg_cost
 return total_cost

np.random.seed(1)

  # Compute Gradient

def compute_multiple_gradient(X, Y, W, b):

  m = X.shape[0]                                                                  #number of samples
  n = X.shape[1]                                                                  #number of features

  dj_dW = np.zeros(n)
  dj_db = 0

  for i in range(m):                                                              #for each sample
    X_i = X[i,:]
    f_xi = np.dot(W, X_i) + b;                                                    #prediction
    err_i = f_xi-Y[i]                                                             #error=prediction-ground_truth
    for j in range(n):                                                            #for each features class
      x_ji = X[i, j]
      #print('f_xi = {}'.format(f_xi));
      #print('Y[i] = {}'.format(Y[i]));
      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i;
      #print('dj_dW[j] = {}'.format(dj_dW[j]))
    dj_db = dj_db + (1/m)*err_i;
  return dj_dW, dj_db

  # Gradiennt Descent

def multiple_gradient_descent (X, Y, W_in, b_in, alpha, num_iters, compute_cost_linear_reg, compute_multiple_gradient):

  W = W_in
  b = b_in



  for itt in range(num_iters):

    dj_dw, dj_db = compute_multiple_gradient(X, Y, W, b)
    W = W - alpha * dj_dw
    b = b - alpha * dj_db
    cost = compute_cost_linear_reg(X, Y, W, b, lamda_)
    if itt % 100 == 0:
        print('Itteration {}:, (W,b) = ({}, {}),\n cost = {}'.format(itt, W, b,cost))
  return W, b, cost






X_train, X_test,Y_train, Y_test = train_test_split(X2, Y2, test_size=0.3)

print("Array originale:\n", X2)
print("Array diviso per colonne:\n X_train:", X_train, "\n X_test:", X_test, "\n Y_train:",Y_train, "\n Y_test:",Y_test)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("Y_train shape:", Y_train.shape)
print("Y_test shape:", Y_test.shape)



X_tmp = X_train
Y_tmp = Y_train

W_in = np.ones(30)
b_in = 1
#b_in = random.uniform(0, 3)

lamda_= 0.1
alpha = 0.001

num_iters = 8000
W,b,cost= multiple_gradient_descent(X_train, Y_train, W_in, b_in, alpha, num_iters, compute_cost_linear_reg, compute_multiple_gradient)

print("W:",W)

print("b:",b)



Y_pred = np.dot(X_test, W) + b

print("Y_predicted:", Y_pred)


mse_tst = mean_squared_error(Y_test, Y_pred)
print(f"Il Mean Squared error del test set è : {mse_tst:.3f}")

Array originale:
 [[2. 2. 3. ... 2. 1. 1.]
 [2. 2. 3. ... 2. 2. 3.]
 [2. 2. 2. ... 1. 2. 2.]
 ...
 [1. 1. 1. ... 1. 4. 3.]
 [2. 1. 2. ... 1. 5. 3.]
 [1. 1. 1. ... 1. 5. 4.]]
Array diviso per colonne:
 X_train: [[2. 1. 3. ... 1. 4. 2.]
 [1. 1. 2. ... 1. 2. 2.]
 [1. 2. 2. ... 1. 3. 4.]
 ...
 [1. 2. 2. ... 2. 3. 3.]
 [2. 1. 2. ... 1. 3. 3.]
 [2. 2. 2. ... 3. 5. 4.]] 
 X_test: [[1. 2. 1. ... 1. 2. 3.]
 [2. 2. 2. ... 3. 5. 4.]
 [1. 1. 2. ... 3. 4. 3.]
 ...
 [2. 1. 3. ... 1. 3. 3.]
 [2. 1. 2. ... 3. 2. 1.]
 [2. 2. 3. ... 1. 4. 3.]] 
 Y_train: [[2.]
 [0.]
 [7.]
 [4.]
 [5.]
 [0.]
 [1.]
 [6.]
 [0.]
 [3.]
 [7.]
 [0.]
 [1.]
 [0.]
 [6.]
 [7.]
 [5.]
 [1.]
 [3.]
 [5.]
 [2.]
 [7.]
 [2.]
 [3.]
 [7.]
 [4.]
 [5.]
 [3.]
 [2.]
 [1.]
 [5.]
 [7.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [2.]
 [3.]
 [1.]
 [1.]
 [1.]
 [0.]
 [2.]
 [7.]
 [6.]
 [0.]
 [6.]
 [2.]
 [3.]
 [3.]
 [2.]
 [7.]
 [1.]
 [4.]
 [1.]
 [1.]
 [4.]
 [4.]
 [2.]
 [4.]
 [2.]
 [3.]
 [2.]
 [1.]
 [7.]
 [1.]
 [5.]
 [5.]
 [1.]
 [7.]
 [3.]
 [1.]
 [1.]
 [6.]
 [5.]
 