<a href="https://colab.research.google.com/github/Tonainings/BigDataProject_Poliba/blob/main/V2_Regularization_ProjectPOLIBA_RegressioneMultipla.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
import math, copy
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [2]:
df=pd.read_csv("_student_prediction.csv")

df.head(10)

STUDENTID  AGE  GENDER  HS_TYPE  SCHOLARSHIP  WORK  ACTIVITY  PARTNER  \
0   STUDENT1    2       2        3            3     1         2        2   
1   STUDENT2    2       2        3            3     1         2        2   
2   STUDENT3    2       2        2            3     2         2        2   
3   STUDENT4    1       1        1            3     1         2        1   
4   STUDENT5    2       2        1            3     2         2        1   
5   STUDENT6    2       2        2            3     2         2        2   
6   STUDENT7    1       2        2            4     2         2        2   
7   STUDENT8    1       1        2            3     1         1        1   
8   STUDENT9    2       1        3            3     2         1        1   
9  STUDENT10    2       1        2            3     2         2        1   

   SALARY  TRANSPORT  ...  PREP_STUDY  PREP_EXAM  NOTES  LISTENS  \
0       1          1  ...           1          1      3        2   
1       1          1  ...           1          1      3        2   
2       2          4  ...           1          1      2        2   
3       2          1  ...           1          2      3        2   
4       3          1  ...           2          1      2        2   
5       2          1  ...           1          1      1        2   
6       1          1  ...           1          1      3        3   
7       2          2  ...           3          1      3        2   
8       1          1  ...           1          1      3        2   
9       3          4  ...           1          1      2        2   

   LIKES_DISCUSS  CLASSROOM  CUML_GPA  EXP_GPA  COURSE ID  GRADE  
0              1          2         1        1          1      1  
1              3          2         2        3          1      1  
2              1          1         2        2          1      1  
3              2          1         3        2          1      1  
4              2          1         2        2          1      1  
5              1          2         4        4          1      2  
6              3          3         4        4          1      5  
7              2          1         1        1          1      2  
8              2          2         4        3          1      5  
9              2          2         1        2          1      0  

[10 rows x 33 columns]

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   STUDENTID      145 non-null    object
 1   AGE            145 non-null    int64 
 2   GENDER         145 non-null    int64 
 3   HS_TYPE        145 non-null    int64 
 4   SCHOLARSHIP    145 non-null    int64 
 5   WORK           145 non-null    int64 
 6   ACTIVITY       145 non-null    int64 
 7   PARTNER        145 non-null    int64 
 8   SALARY         145 non-null    int64 
 9   TRANSPORT      145 non-null    int64 
 10  LIVING         145 non-null    int64 
 11  MOTHER_EDU     145 non-null    int64 
 12  FATHER_EDU     145 non-null    int64 
 13  #_SIBLINGS     145 non-null    int64 
 14  KIDS           145 non-null    int64 
 15  MOTHER_JOB     145 non-null    int64 
 16  FATHER_JOB     145 non-null    int64 
 17  STUDY_HRS      145 non-null    int64 
 18  READ_FREQ      145 non-null   

In [4]:
X1 = df[['AGE', 'GENDER', 'HS_TYPE', 'SCHOLARSHIP', 'WORK', 'ACTIVITY', 'PARTNER', 'SALARY', 'TRANSPORT', 'LIVING', 'MOTHER_EDU', 'FATHER_EDU', '#_SIBLINGS', 'KIDS', 'MOTHER_JOB', 'FATHER_JOB', 'STUDY_HRS', 'READ_FREQ', 'READ_FREQ_SCI', 'ATTEND_DEPT', 'IMPACT', 'ATTEND', 'PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS', 'LIKES_DISCUSS', 'CLASSROOM', 'CUML_GPA', 'EXP_GPA']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X2 = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
                                                                #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
Y2 = np.array(Y1, dtype=float)



print(X2)



print(Y2)



[[2. 2. 3. ... 2. 1. 1.]
 [2. 2. 3. ... 2. 2. 3.]
 [2. 2. 2. ... 1. 2. 2.]
 ...
 [1. 1. 1. ... 1. 4. 3.]
 [2. 1. 2. ... 1. 5. 3.]
 [1. 1. 1. ... 1. 5. 4.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [5.]
 [2.]
 [5.]
 [0.]
 [2.]
 [0.]
 [0.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [5.]
 [5.]
 [3.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [1.]
 [2.]
 [1.]
 [4.]
 [1.]
 [5.]
 [3.]
 [3.]
 [5.]
 [4.]
 [3.]
 [5.]
 [2.]
 [5.]
 [3.]
 [5.]
 [3.]
 [2.]
 [5.]
 [1.]
 [5.]
 [5.]
 [7.]
 [6.]
 [6.]
 [6.]
 [7.]
 [7.]
 [4.]
 [7.]
 [4.]
 [3.]
 [4.]
 [3.]
 [7.]
 [7.]
 [7.]
 [4.]
 [5.]
 [6.]
 [6.]
 [6.]
 [6.]
 [6.]
 [7.]
 [4.]
 [6.]
 [5.]
 [7.]
 [6.]
 [7.]
 [7.]
 [6.]
 [7.]
 [7.]
 [7.]
 [3.]
 [7.]
 [7.]
 [6.]
 [6.]
 [7.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [1.]
 [0.]
 [2.]
 [1.]
 [3.]
 [2.]
 [3.]
 [1.]
 [0.]
 [3.]
 [1.]
 [4.]
 [3.]
 [3.]
 [1.]
 [2.]
 [0.]
 [2.]
 [0.]
 [0.]
 [5.

Squared normalization

In [5]:
X = normalize(X2, norm='l2')

MinMaxRegularization

In [11]:
scaler = MinMaxScaler(feature_range=(0, 10))                                      # regularization

X = scaler.fit_transform(X2)



scaler = MinMaxScaler(feature_range=(0, 30))

Y = scaler.fit_transform(Y2)

print(X)
print(Y)

[[ 5.         10.         10.         ...  5.          0.
   0.        ]
 [ 5.         10.         10.         ...  5.          2.5
   6.66666667]
 [ 5.         10.          5.         ...  0.          2.5
   3.33333333]
 ...
 [ 0.          0.          0.         ...  0.          7.5
   6.66666667]
 [ 5.          0.          5.         ...  0.         10.
   6.66666667]
 [ 0.          0.          0.         ...  0.         10.
  10.        ]]
[[ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 8.57142857]
 [21.42857143]
 [ 8.57142857]
 [21.42857143]
 [ 0.        ]
 [ 8.57142857]
 [ 0.        ]
 [ 0.        ]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [12.85714286]
 [ 4.28571429]
 [ 4.28571429]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [12.85714286]
 [ 4.28571429]
 [ 4.28571429]
 [12.85714286]
 [21.42857143]
 [21.42857143]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857

In [7]:
print(X.shape)
print(Y.shape)

(145, 30)
(145, 1)


# Multiple Linear Regression to predict Y from X

In [8]:
def compute_multiple_cost(X, Y, W, b):

  m = X.shape[0]

  cost = 0

  for i in range(m):   #for i = 1 : m
    X_i = X[i,:]
    f_Wb = np.dot(W, X_i) + b
    err_i = (f_Wb - Y[i])**2
    cost = cost + err_i
    total_cost=(1/(2*m))*cost
  return total_cost


W = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])
#W = np.random.randn(30)
b = 0

total_cost = compute_multiple_cost(X, Y, W, b)


print ('for b={} and W randomic, total_cost={}'.format(b,total_cost))

for b=0 and W randomic, total_cost=[5804.33371061]


In [9]:
def compute_multiple_gradient(X, Y, W, b):

  m = X.shape[0] #number of samples
  n = X.shape[1] #number of features

  dj_dW = np.zeros(n)
  dj_db = 0

  for i in range(m): #for each sample
    X_i = X[i,:]
    f_xi = np.dot(W, X_i) + b; #prediction
    err_i = f_xi-Y[i]   #error=prediction-ground_truth
    for j in range(n): #for each features class
      x_ji = X[i, j]
      #print('f_xi = {}'.format(f_xi));
      #print('Y[i] = {}'.format(Y[i]));
      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i;
      #print('dj_dW[j] = {}'.format(dj_dW[j]))
    dj_db = dj_db + (1/m)*err_i;
  return dj_dW, dj_db

W = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])
#W = np.random.randn(30)
b = 0

dj_dW, dj_db = compute_multiple_gradient(X, Y, W, b)
#print(dj_dW,dj_db)

In [10]:
def multiple_gradient_descent (X, Y, W_in, b_in, alpha, num_iters, compute_multiple_cost, compute_multiple_gradient):

  W = W_in
  b = b_in



  for itt in range(num_iters):

    dj_dw, dj_db = compute_multiple_gradient(X, Y, W, b)
    W = W - alpha * dj_dw
    b = b - alpha * dj_db
    cost = compute_multiple_cost(X, Y, W, b)
    if itt % 100 == 0:
        print('Itteration {}:, (W,b) = ({}, {}),\n cost = {}'.format(itt, W, b,cost))
  return W, b, cost




#W_in = np.random.randn(30)
W_in = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])
b_in = 0
alpha = 0.003
#alpha = 0.003282 #convergenza meno lenta §25
#alpha = 0.0001   #convergenza lenta
num_iters = 1000
multiple_gradient_descent(X, Y, W_in, b_in, alpha, num_iters, compute_multiple_cost, compute_multiple_gradient)


Itteration 0:, (W,b) = ([-0.03425369 -0.95603941 -0.51733498 -1.05363547 -1.13323153 -0.9837734
 -0.90283251  0.48198645  0.2904023   0.22623645  0.16708374 -0.05126305
 -0.45505172  0.70313793 -0.08347783 -0.45127833  0.02487315 -0.520867
 -0.64606404  0.26287192  0.6360197   0.18376355  0.44872414  0.71629557
 -1.49894581 -0.68383251 -1.25278079 -0.35934483 -0.7261564  -0.88586371], [-0.31798867]),
 cost = [3985.90599135]
Itteration 100:, (W,b) = ([-0.56149227  0.51341946  0.46132072 -0.04444666  0.40185347 -0.10083225
  0.0285379  -0.27692276 -0.45739214  0.40579528  0.2026312   0.07770015
  0.16060077  0.29131172  0.07565792 -0.22672532 -0.05982691  0.64504009
 -0.0743971  -0.12662312 -0.2670991  -0.0381539   0.10592592  0.3333023
 -0.10281097  0.49305063  0.05522103 -0.04003474  0.60583749  0.06755017], [-0.1892253]),
 cost = [26.45076016]
Itteration 200:, (W,b) = ([-0.74307959  0.4919347   0.54049983 -0.11915968  0.38543145 -0.02653258
  0.03343422 -0.32475159 -0.50641363  0.4634

(array([-0.85665236,  0.48234689,  0.58073715, -0.2667778 ,  0.39257985,
        -0.00234609,  0.05269256, -0.29818955, -0.50646043,  0.51586544,
         0.20825644, -0.04786754,  0.05104276,  0.40824831, -0.02925164,
        -0.33442944, -0.20612467,  0.95988293, -0.02200644, -0.1436158 ,
        -0.3945271 ,  0.00247411,  0.17427187,  0.22860005, -0.03820713,
         0.56532465,  0.03952011, -0.08481377,  0.86897651, -0.04420261]),
 array([-0.03424486]),
 array([25.68219296]))