<a href="https://colab.research.google.com/github/Tonainings/BigDataProject_Poliba/blob/main/V3_Regularization_ProjectPOLIBA_RegressioneMultipla.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
import math, copy
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [2]:
df=pd.read_csv("_student_prediction.csv")

df.head(10)

STUDENTID  AGE  GENDER  HS_TYPE  SCHOLARSHIP  WORK  ACTIVITY  PARTNER  \
0   STUDENT1    2       2        3            3     1         2        2   
1   STUDENT2    2       2        3            3     1         2        2   
2   STUDENT3    2       2        2            3     2         2        2   
3   STUDENT4    1       1        1            3     1         2        1   
4   STUDENT5    2       2        1            3     2         2        1   
5   STUDENT6    2       2        2            3     2         2        2   
6   STUDENT7    1       2        2            4     2         2        2   
7   STUDENT8    1       1        2            3     1         1        1   
8   STUDENT9    2       1        3            3     2         1        1   
9  STUDENT10    2       1        2            3     2         2        1   

   SALARY  TRANSPORT  ...  PREP_STUDY  PREP_EXAM  NOTES  LISTENS  \
0       1          1  ...           1          1      3        2   
1       1          1  ...           1          1      3        2   
2       2          4  ...           1          1      2        2   
3       2          1  ...           1          2      3        2   
4       3          1  ...           2          1      2        2   
5       2          1  ...           1          1      1        2   
6       1          1  ...           1          1      3        3   
7       2          2  ...           3          1      3        2   
8       1          1  ...           1          1      3        2   
9       3          4  ...           1          1      2        2   

   LIKES_DISCUSS  CLASSROOM  CUML_GPA  EXP_GPA  COURSE ID  GRADE  
0              1          2         1        1          1      1  
1              3          2         2        3          1      1  
2              1          1         2        2          1      1  
3              2          1         3        2          1      1  
4              2          1         2        2          1      1  
5              1          2         4        4          1      2  
6              3          3         4        4          1      5  
7              2          1         1        1          1      2  
8              2          2         4        3          1      5  
9              2          2         1        2          1      0  

[10 rows x 33 columns]

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   STUDENTID      145 non-null    object
 1   AGE            145 non-null    int64 
 2   GENDER         145 non-null    int64 
 3   HS_TYPE        145 non-null    int64 
 4   SCHOLARSHIP    145 non-null    int64 
 5   WORK           145 non-null    int64 
 6   ACTIVITY       145 non-null    int64 
 7   PARTNER        145 non-null    int64 
 8   SALARY         145 non-null    int64 
 9   TRANSPORT      145 non-null    int64 
 10  LIVING         145 non-null    int64 
 11  MOTHER_EDU     145 non-null    int64 
 12  FATHER_EDU     145 non-null    int64 
 13  #_SIBLINGS     145 non-null    int64 
 14  KIDS           145 non-null    int64 
 15  MOTHER_JOB     145 non-null    int64 
 16  FATHER_JOB     145 non-null    int64 
 17  STUDY_HRS      145 non-null    int64 
 18  READ_FREQ      145 non-null   

In [3]:
X1 = df[['AGE', 'GENDER', 'HS_TYPE', 'SCHOLARSHIP', 'WORK', 'ACTIVITY', 'PARTNER', 'SALARY', 'TRANSPORT', 'LIVING', 'MOTHER_EDU', 'FATHER_EDU', '#_SIBLINGS', 'KIDS', 'MOTHER_JOB', 'FATHER_JOB', 'STUDY_HRS', 'READ_FREQ', 'READ_FREQ_SCI', 'ATTEND_DEPT', 'IMPACT', 'ATTEND', 'PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS', 'LIKES_DISCUSS', 'CLASSROOM', 'CUML_GPA', 'EXP_GPA']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X2 = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
                                                                #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
Y2 = np.array(Y1, dtype=float)



print(X2)



print(Y2)



[[2. 2. 3. ... 2. 1. 1.]
 [2. 2. 3. ... 2. 2. 3.]
 [2. 2. 2. ... 1. 2. 2.]
 ...
 [1. 1. 1. ... 1. 4. 3.]
 [2. 1. 2. ... 1. 5. 3.]
 [1. 1. 1. ... 1. 5. 4.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [5.]
 [2.]
 [5.]
 [0.]
 [2.]
 [0.]
 [0.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [5.]
 [5.]
 [3.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [1.]
 [2.]
 [1.]
 [4.]
 [1.]
 [5.]
 [3.]
 [3.]
 [5.]
 [4.]
 [3.]
 [5.]
 [2.]
 [5.]
 [3.]
 [5.]
 [3.]
 [2.]
 [5.]
 [1.]
 [5.]
 [5.]
 [7.]
 [6.]
 [6.]
 [6.]
 [7.]
 [7.]
 [4.]
 [7.]
 [4.]
 [3.]
 [4.]
 [3.]
 [7.]
 [7.]
 [7.]
 [4.]
 [5.]
 [6.]
 [6.]
 [6.]
 [6.]
 [6.]
 [7.]
 [4.]
 [6.]
 [5.]
 [7.]
 [6.]
 [7.]
 [7.]
 [6.]
 [7.]
 [7.]
 [7.]
 [3.]
 [7.]
 [7.]
 [6.]
 [6.]
 [7.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [1.]
 [0.]
 [2.]
 [1.]
 [3.]
 [2.]
 [3.]
 [1.]
 [0.]
 [3.]
 [1.]
 [4.]
 [3.]
 [3.]
 [1.]
 [2.]
 [0.]
 [2.]
 [0.]
 [0.]
 [5.

Squared normalization

In [ ]:
X = normalize(X2, norm='l2')

MinMaxRegularization

In [4]:
scaler = MinMaxScaler(feature_range=(0, 10))                                      # regularization

X = scaler.fit_transform(X2)



scaler = MinMaxScaler(feature_range=(0, 30))

Y1 = scaler.fit_transform(Y2)
Y = np.ravel(Y1)                                                                   # Appiattisce y
print(X)
print(Y)

[[ 5.         10.         10.         ...  5.          0.
   0.        ]
 [ 5.         10.         10.         ...  5.          2.5
   6.66666667]
 [ 5.         10.          5.         ...  0.          2.5
   3.33333333]
 ...
 [ 0.          0.          0.         ...  0.          7.5
   6.66666667]
 [ 5.          0.          5.         ...  0.         10.
   6.66666667]
 [ 0.          0.          0.         ...  0.         10.
  10.        ]]
[ 4.28571429  4.28571429  4.28571429  4.28571429  4.28571429  8.57142857
 21.42857143  8.57142857 21.42857143  0.          8.57142857  0.
  0.          4.28571429  8.57142857  8.57142857  4.28571429  8.57142857
  8.57142857 12.85714286  4.28571429  4.28571429 12.85714286  4.28571429
  8.57142857 12.85714286  4.28571429  4.28571429 12.85714286 21.42857143
 21.42857143 12.85714286  4.28571429  8.57142857  8.57142857  4.28571429
  8.57142857  4.28571429  8.57142857  4.28571429  4.28571429  4.28571429
  4.28571429 17.14285714  4.28571429 12.85714286 2

In [5]:
print(X.shape)
print(Y.shape)

(145, 30)
(145,)


# Multiple Linear Regression to predict Y from X

In [6]:
def compute_multiple_cost(X, Y, W, b):

  m = X.shape[0]

  cost = 0

  for i in range(m):   #for i = 1 : m
    X_i = X[i,:]
    f_Wb = np.dot(W, X_i) + b
    err_i = (f_Wb - Y[i])**2
    cost = cost + err_i
    total_cost=(1/(2*m))*cost
  return total_cost


W = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])
#W = np.random.randn(30)
b = 0

total_cost = compute_multiple_cost(X, Y, W, b)


print ('for b={} and W randomic, total_cost={}'.format(b,total_cost))

for b=0 and W randomic, total_cost=5804.333710610677


In [7]:
def compute_multiple_gradient(X, Y, W, b):

  m = X.shape[0] #number of samples
  n = X.shape[1] #number of features

  dj_dW = np.zeros(n)
  dj_db = 0

  for i in range(m): #for each sample
    X_i = X[i,:]
    f_xi = np.dot(W, X_i) + b; #prediction
    err_i = f_xi-Y[i]   #error=prediction-ground_truth
    for j in range(n): #for each features class
      x_ji = X[i, j]
      #print('f_xi = {}'.format(f_xi));
      #print('Y[i] = {}'.format(Y[i]));
      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i;
      #print('dj_dW[j] = {}'.format(dj_dW[j]))
    dj_db = dj_db + (1/m)*err_i;
  return dj_dW, dj_db

W = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])
#W = np.random.randn(30)
b = 0

dj_dW, dj_db = compute_multiple_gradient(X, Y, W, b)
#print(dj_dW,dj_db)

In [15]:
def multiple_gradient_descent (X, Y, W_in, b_in, alpha, num_iters, compute_multiple_cost, compute_multiple_gradient):

  W = W_in
  b = b_in



  for itt in range(num_iters):

    dj_dw, dj_db = compute_multiple_gradient(X, Y, W, b)
    W = W - alpha * dj_dw
    b = b - alpha * dj_db
    cost = compute_multiple_cost(X, Y, W, b)
    if itt % 100 == 0:
        print('Itteration {}:, (W,b) = ({}, {}),\n cost = {}'.format(itt, W, b,cost))
  return W, b, cost




#W_in = np.random.randn(30)
W_in = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])
b_in = 0
#alpha = 0.003
alpha = 0.003282 #convergenza meno lenta §25
#alpha = 0.0001   #convergenza lenta
num_iters = 10000
multiple_gradient_descent(X, Y, W_in, b_in, alpha, num_iters, compute_multiple_cost, compute_multiple_gradient)


Itteration 0:, (W,b) = ([-0.13147354 -1.13990711 -0.65996446 -1.2466772  -1.33375529 -1.1702481
 -1.08169877  0.43329318  0.22370011  0.15350268  0.08878962 -0.15008178
 -0.59182659  0.6752329  -0.18532475 -0.58769849 -0.06678877 -0.66382849
 -0.80079406  0.19358188  0.60180556  0.10703732  0.39690421  0.68962735
 -1.73384672 -0.84211277 -1.46454218 -0.48712324 -0.88841511 -1.0631349 ], -0.3478796049261085),
 cost = 5770.980312341916
Itteration 100:, (W,b) = ([-1.03653103 -0.38738613 -0.19734142 -0.95969542 -0.57245678 -0.97134132
 -0.81359749 -0.50133227 -0.76241535  0.08209703 -0.15896775 -0.39258133
 -0.50480088  0.1747838  -0.39876132 -0.87971511 -0.5009254   0.00319986
 -0.79175073 -0.43184903 -0.42359353 -0.37317322 -0.11674468  0.20477261
 -1.20853659 -0.24183595 -0.95288693 -0.65312931 -0.16008715 -0.78169412], -0.32851938044481677),
 cost = 3778.604652799171
Itteration 200:, (W,b) = ([-1.12343763e+00 -2.40685088e-01  5.21942383e-04 -8.72685477e-01
 -4.03762123e-01 -7.37480863e

(array([-0.87980028,  0.47670518,  0.56217514, -0.32118397,  0.37998119,
        -0.01214451,  0.04690063, -0.31221175, -0.50295756,  0.50161109,
         0.20164125, -0.06557884,  0.03543084,  0.41064957, -0.06686738,
        -0.34914382, -0.22646747,  0.95022169, -0.03196704, -0.13920619,
        -0.40051017, -0.00599129,  0.17039691,  0.21941821, -0.05450543,
         0.55303741,  0.03146849, -0.08078671,  0.87087541, -0.04059727]),
 1.4798371995387456,
 25.604054587772044)