<a href="https://colab.research.google.com/github/Tonainings/BigDataProject_Poliba/blob/main/V3_Regularization_ProjectPOLIBA_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
import math, copy
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [2]:
df=pd.read_csv("_student_prediction.csv")

df.head(10)

STUDENTID  AGE  GENDER  HS_TYPE  SCHOLARSHIP  WORK  ACTIVITY  PARTNER  \
0   STUDENT1    2       2        3            3     1         2        2   
1   STUDENT2    2       2        3            3     1         2        2   
2   STUDENT3    2       2        2            3     2         2        2   
3   STUDENT4    1       1        1            3     1         2        1   
4   STUDENT5    2       2        1            3     2         2        1   
5   STUDENT6    2       2        2            3     2         2        2   
6   STUDENT7    1       2        2            4     2         2        2   
7   STUDENT8    1       1        2            3     1         1        1   
8   STUDENT9    2       1        3            3     2         1        1   
9  STUDENT10    2       1        2            3     2         2        1   

   SALARY  TRANSPORT  ...  PREP_STUDY  PREP_EXAM  NOTES  LISTENS  \
0       1          1  ...           1          1      3        2   
1       1          1  ...           1          1      3        2   
2       2          4  ...           1          1      2        2   
3       2          1  ...           1          2      3        2   
4       3          1  ...           2          1      2        2   
5       2          1  ...           1          1      1        2   
6       1          1  ...           1          1      3        3   
7       2          2  ...           3          1      3        2   
8       1          1  ...           1          1      3        2   
9       3          4  ...           1          1      2        2   

   LIKES_DISCUSS  CLASSROOM  CUML_GPA  EXP_GPA  COURSE ID  GRADE  
0              1          2         1        1          1      1  
1              3          2         2        3          1      1  
2              1          1         2        2          1      1  
3              2          1         3        2          1      1  
4              2          1         2        2          1      1  
5              1          2         4        4          1      2  
6              3          3         4        4          1      5  
7              2          1         1        1          1      2  
8              2          2         4        3          1      5  
9              2          2         1        2          1      0  

[10 rows x 33 columns]

In [ ]:
print(df.info())

In [14]:
X1 = df[['AGE', 'GENDER', 'HS_TYPE', 'SCHOLARSHIP', 'WORK', 'ACTIVITY', 'PARTNER', 'SALARY', 'TRANSPORT', 'LIVING', 'MOTHER_EDU', 'FATHER_EDU', '#_SIBLINGS', 'KIDS', 'MOTHER_JOB', 'FATHER_JOB', 'STUDY_HRS', 'READ_FREQ', 'READ_FREQ_SCI', 'ATTEND_DEPT', 'IMPACT', 'ATTEND', 'PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS', 'LIKES_DISCUSS', 'CLASSROOM', 'CUML_GPA', 'EXP_GPA']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X2 = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
                                                                #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
Y2 = np.array(Y1, dtype=float)



print(X2)
print(Y2)

W = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])
b = 0

[[2. 2. 3. ... 2. 1. 1.]
 [2. 2. 3. ... 2. 2. 3.]
 [2. 2. 2. ... 1. 2. 2.]
 ...
 [1. 1. 1. ... 1. 4. 3.]
 [2. 1. 2. ... 1. 5. 3.]
 [1. 1. 1. ... 1. 5. 4.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [5.]
 [2.]
 [5.]
 [0.]
 [2.]
 [0.]
 [0.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [5.]
 [5.]
 [3.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [1.]
 [2.]
 [1.]
 [4.]
 [1.]
 [5.]
 [3.]
 [3.]
 [5.]
 [4.]
 [3.]
 [5.]
 [2.]
 [5.]
 [3.]
 [5.]
 [3.]
 [2.]
 [5.]
 [1.]
 [5.]
 [5.]
 [7.]
 [6.]
 [6.]
 [6.]
 [7.]
 [7.]
 [4.]
 [7.]
 [4.]
 [3.]
 [4.]
 [3.]
 [7.]
 [7.]
 [7.]
 [4.]
 [5.]
 [6.]
 [6.]
 [6.]
 [6.]
 [6.]
 [7.]
 [4.]
 [6.]
 [5.]
 [7.]
 [6.]
 [7.]
 [7.]
 [6.]
 [7.]
 [7.]
 [7.]
 [3.]
 [7.]
 [7.]
 [6.]
 [6.]
 [7.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [1.]
 [0.]
 [2.]
 [1.]
 [3.]
 [2.]
 [3.]
 [1.]
 [0.]
 [3.]
 [1.]
 [4.]
 [3.]
 [3.]
 [1.]
 [2.]
 [0.]
 [2.]
 [0.]
 [0.]
 [5.

Squared normalization

In [ ]:
X = normalize(X2, norm='l2')

MinMaxRegularization

In [15]:
scaler = MinMaxScaler(feature_range=(0, 10))                                      # regularization

X = scaler.fit_transform(X2)



scaler = MinMaxScaler(feature_range=(0, 30))

y1 = scaler.fit_transform(Y2)

print(X)
print(y1)

[[ 5.         10.         10.         ...  5.          0.
   0.        ]
 [ 5.         10.         10.         ...  5.          2.5
   6.66666667]
 [ 5.         10.          5.         ...  0.          2.5
   3.33333333]
 ...
 [ 0.          0.          0.         ...  0.          7.5
   6.66666667]
 [ 5.          0.          5.         ...  0.         10.
   6.66666667]
 [ 0.          0.          0.         ...  0.         10.
  10.        ]]
[[ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 8.57142857]
 [21.42857143]
 [ 8.57142857]
 [21.42857143]
 [ 0.        ]
 [ 8.57142857]
 [ 0.        ]
 [ 0.        ]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [12.85714286]
 [ 4.28571429]
 [ 4.28571429]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [12.85714286]
 [ 4.28571429]
 [ 4.28571429]
 [12.85714286]
 [21.42857143]
 [21.42857143]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857

In [18]:
print(X.shape)
print(y.shape)

(145, 30)
(145,)


# Logistic Regression

In [19]:
def sig(x):
 return 1/(1 + np.exp(-x))

Cost compute

In [20]:
def compute_multiple_cost(X, y, W, b):

  m = X.shape[0]
  cost = 0

  for i in range(m):
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i)
    cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
  total_cost = (1/(2*m))*cost
  return total_cost

total_cost = compute_multiple_cost(X, y, W, b)



print ('for b={}, total_cost={}'.format(b,total_cost))



for b=0, total_cost=nan


<ipython-input-20-024f0b29a243>:9: RuntimeWarning: divide by zero encountered in log
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
<ipython-input-20-024f0b29a243>:9: RuntimeWarning: invalid value encountered in double_scalars
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)


Gradient compute

In [21]:
def compute_multiple_gradient(X, y, W, b):

  m = X.shape[0] # Number of training samples
  n = X.shape[1] # Number of feature classes

  dj_dW = np.zeros(n)
  dj_db = 0

  for i in range(m): # For each sample
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i) # Prediction
    err_i = f_xi - y[i] # Prediction - Ground truth
    for j in range(n): # For each feature
      x_ji = X[i,j]
      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i
    dj_db = dj_db + (1/m)*err_i
  return dj_dW, dj_db

dj_dW, dj_db = compute_multiple_gradient(X, y, W, b)
print(dj_dW, dj_db)


[2.24137931 3.44827586 3.         4.29310345 4.06896552 4.27586207
 4.06896552 1.29310345 1.56321839 1.54022989 1.68275862 2.12413793
 2.93103448 0.48275862 2.34482759 3.03448276 2.0862069  2.96551724
 3.37931034 1.72413793 0.96551724 1.79310345 1.13793103 0.55172414
 5.17241379 3.48275862 4.62068966 2.55172414 3.22413793 3.6091954 ] 0.6758620689655183


Gradient descent

In [30]:
def multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters,  cost_function, gradient_function):

  W = W_in
  b = b_in

  for itt in range(num_iters):
    dj_dw, dj_db = compute_multiple_gradient(X, y, W, b)
    W = W - alpha*dj_dw
    b = b - alpha*dj_db
    cost = compute_multiple_cost(X, y, W, b)

    if itt % 100 == 0:
      print('Iteration {}: (w,b) = ({}, {}),\n cost = {}'.format(itt, W, b, cost))

  return W, b, cost

W_in = np.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ])
b_in = 1

alpha = 0.008
num_iters = 10000

multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters, compute_multiple_cost, compute_multiple_gradient)


<ipython-input-20-024f0b29a243>:9: RuntimeWarning: divide by zero encountered in log
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
<ipython-input-20-024f0b29a243>:9: RuntimeWarning: invalid value encountered in double_scalars
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)


Iteration 0: (w,b) = ([0.98206897 0.97241379 0.976      0.96565517 0.96744828 0.9657931
 0.96744828 0.98965517 0.98749425 0.98767816 0.98653793 0.9830069
 0.97655172 0.99613793 0.98124138 0.97572414 0.98331034 0.97627586
 0.97296552 0.9862069  0.99227586 0.98565517 0.99089655 0.99558621
 0.95862069 0.97213793 0.96303448 0.97958621 0.9742069  0.97112644], 0.9945931034482759),
 cost = nan
Iteration 100: (w,b) = ([ 0.077953    0.21083704  0.08900316 -0.38039041  0.05120777 -0.2636774
 -0.21328237  0.26849519  0.22634205  0.35797658  0.31337222  0.21734739
  0.22776033  0.66600577  0.0451764  -0.03943687  0.21972111  0.06976033
 -0.14387478  0.19824696  0.36844516  0.14712455  0.36191015  0.69924355
 -0.59972894 -0.12404911 -0.35884637  0.22994069  0.15298133 -0.06939693], 0.7678612846063305),
 cost = 0.9171127206771389
Iteration 200: (w,b) = ([-0.15702484  0.23601943  0.17332352 -0.33292907  0.17742215 -0.19208307
 -0.05686437 -0.05867933  0.006599    0.29845026  0.13432995  0.0594038
  0

(array([-0.32724792,  0.13310513,  0.19824194, -0.23726326,  0.17113917,
        -0.04364013, -0.00722477, -0.40236336, -0.13351498,  0.30966413,
         0.04124107, -0.05876166,  0.04189047,  0.21490622, -0.35916664,
        -0.15627813, -0.1785825 ,  0.23863826,  0.02538719, -0.05849059,
        -0.28545326,  0.01025667,  0.09572727, -0.04699429, -0.08100505,
         0.01797571, -0.12085029, -0.01507197,  0.32482853, -0.07503954]),
 0.09408057899842644,
 0.2038931348334488)