<a href="https://colab.research.google.com/github/Tonainings/BigDataProject_Poliba/blob/main/13/10_ProjectPOLIBA_LogisticRegression_meeting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
df= pd.read_csv("_student_prediction.csv")


#x_train = np.array(df["CUML_GPA"])   #una variabile da 145 valori
#y_train = np.array(df["GRADE"])

print(df.info())

#X = np.array([df["PREP_STUDY"],df["PREP_EXAM"],df["NOTES"],df["LISTENS"]])       # 4 variabili da 145 valori per ognuno
#Y = np.array(df["GRADE"])
#W = np.array([-4.0, 1.0, 1.0, 1.0])
#b = 0


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   STUDENTID      145 non-null    object
 1   AGE            145 non-null    int64 
 2   GENDER         145 non-null    int64 
 3   HS_TYPE        145 non-null    int64 
 4   SCHOLARSHIP    145 non-null    int64 
 5   WORK           145 non-null    int64 
 6   ACTIVITY       145 non-null    int64 
 7   PARTNER        145 non-null    int64 
 8   SALARY         145 non-null    int64 
 9   TRANSPORT      145 non-null    int64 
 10  LIVING         145 non-null    int64 
 11  MOTHER_EDU     145 non-null    int64 
 12  FATHER_EDU     145 non-null    int64 
 13  #_SIBLINGS     145 non-null    int64 
 14  KIDS           145 non-null    int64 
 15  MOTHER_JOB     145 non-null    int64 
 16  FATHER_JOB     145 non-null    int64 
 17  STUDY_HRS      145 non-null    int64 
 18  READ_FREQ      145 non-null   

In [4]:
#df.sort_values(by=['GRADE'], ascending= TRUE, implace= TRUE)                     #sort by

df.head(10)  #mostra i primi 10 record


STUDENTID  AGE  GENDER  HS_TYPE  SCHOLARSHIP  WORK  ACTIVITY  PARTNER  \
0   STUDENT1    2       2        3            3     1         2        2   
1   STUDENT2    2       2        3            3     1         2        2   
2   STUDENT3    2       2        2            3     2         2        2   
3   STUDENT4    1       1        1            3     1         2        1   
4   STUDENT5    2       2        1            3     2         2        1   
5   STUDENT6    2       2        2            3     2         2        2   
6   STUDENT7    1       2        2            4     2         2        2   
7   STUDENT8    1       1        2            3     1         1        1   
8   STUDENT9    2       1        3            3     2         1        1   
9  STUDENT10    2       1        2            3     2         2        1   

   SALARY  TRANSPORT  ...  PREP_STUDY  PREP_EXAM  NOTES  LISTENS  \
0       1          1  ...           1          1      3        2   
1       1          1  ...           1          1      3        2   
2       2          4  ...           1          1      2        2   
3       2          1  ...           1          2      3        2   
4       3          1  ...           2          1      2        2   
5       2          1  ...           1          1      1        2   
6       1          1  ...           1          1      3        3   
7       2          2  ...           3          1      3        2   
8       1          1  ...           1          1      3        2   
9       3          4  ...           1          1      2        2   

   LIKES_DISCUSS  CLASSROOM  CUML_GPA  EXP_GPA  COURSE ID  GRADE  
0              1          2         1        1          1      1  
1              3          2         2        3          1      1  
2              1          1         2        2          1      1  
3              2          1         3        2          1      1  
4              2          1         2        2          1      1  
5              1          2         4        4          1      2  
6              3          3         4        4          1      5  
7              2          1         1        1          1      2  
8              2          2         4        3          1      5  
9              2          2         1        2          1      0  

[10 rows x 33 columns]

In [6]:
from sklearn.preprocessing import normalize

#X1 = df[['PREP_STUDY']].to_numpy()
X1 = df[['PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X2 = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
#X2 = np.array(X1, dtype=float)
#X = X2.transpose()                                                                 #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
y = np.array(Y1, dtype=float)
#Y2 = np.array(Y1, dtype=float)
#Y = Y2.transpose()




X = normalize(X2, norm='l2')                                              #https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html#sklearn.preprocessing.normalize
                                                                                      #l1 for each non-zeros, norm. indipendent
#X3 = normalize(X2, norm='l1')
                                                                                      #l2 for each non-zeros, norm. for feature
W = np.array([-4.0, 1.0, 1.0, 1.0])
b = 0

#print(X)
#print(y)




In [ ]:
"""from sklearn.preprocessing import normalize
#X1 = df[['PREP_STUDY']].to_numpy()
X1 = df[['PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
#X2 = np.array(X1, dtype=float)
#X = X2.transpose()                                                                 #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
y = np.array(Y1, dtype=float)
#Y2 = np.array(Y1, dtype=float)
#Y = Y2.transpose()



#print(X)
#print(y)
#print(W)

#print(type(X))                                                                      #stampa il tipo di variabile
#print(X.dtype)                                                                      #stampa il formato dei valori di una variabile
#print(type(y))
#print(y.dtype)
#print(type(W))
#print(W.dtype)

#x_train = np.array(df["CUML_GPA"])   #una variabile da 145 valori
#y_train = np.array(df["GRADE"])

#X = np.array([df["PREP_STUDY"],df["PREP_EXAM"],df["NOTES"],df["LISTENS"]])       # 4 variabili da 145 valori per ognuno
#Y = np.array(df["GRADE"])

#W = np.array([-4.0, 1.0, 1.0, 1.0])
#b = 0

#print(x_train)
#print(y_train)


Cost compute

In [9]:
#import numpy as np
def sig(x):
 return 1/(1 + np.exp(-x))

def compute_multiple_cost(X, y, W, b):

  m = X.shape[0]
  cost = 0

  for i in range(m):
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i)
    cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)                          #+ delta * norm(x_i) overfitting divergence
  total_cost = (1/(2*m))*cost
  return total_cost

total_cost = compute_multiple_cost(X, y, W, b)



print ('for b={}, total_cost={}'.format(b,total_cost))

for b=0, total_cost=[0.17489831]


Gradient compute

In [10]:
def compute_multiple_gradient(X, y, W, b):

  m = X.shape[0] # Number of training samples
  n = X.shape[1] # Number of feature classes

  dj_dW = np.zeros(n)
  dj_db = 0

  for i in range(m): # For each sample
    z_i = np.dot(X[i],W) + b
    f_xi = sig(z_i) # Prediction
    err_i = f_xi - y[i] # Prediction - Ground truth
    for j in range(n): # For each feature
      x_ji = X[i,j]
      dj_dW[j] = dj_dW[j] + (1/m)*x_ji*err_i
    dj_db = dj_db + (1/m)*err_i
  return dj_dW, dj_db

dj_dW, dj_db = compute_multiple_gradient(X, y, W, b)
print(dj_dW, dj_db)

[-0.93610664 -0.82421162 -1.77976468 -1.44039099] [-2.69448269]


In [ ]:
print(X)
print(y)

Gradient descent

In [12]:
def multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters,  cost_function, gradient_function):

  W = W_in
  b = b_in

  for itt in range(num_iters):
    dj_dw, dj_db = compute_multiple_gradient(X, y, W, b)
    W = W - alpha*dj_dw
    b = b - alpha*dj_db
    cost = compute_multiple_cost(X, y, W, b)

    if itt % 100 == 0:
      print('Iteration {}: (w,b) = ({}, {}), cost = {}'.format(itt, W, b, cost))

  return W, b, cost

W_in = np.array([-4.0, 1.0, 1.0, 1.0])
b_in = 1

alpha = 0.002
num_iters = 5000

multiple_gradient_descent(X, y,  W_in, b_in, alpha,  num_iters, compute_multiple_cost, compute_multiple_gradient)

Iteration 0: (w,b) = ([-3.99827369  1.00152199  1.00328507  1.00266159], [1.00497513]), cost = [-1.13030155]
Iteration 100: (w,b) = ([-3.83114402  1.14932946  1.32241369  1.26134282], [1.48809442]), cost = [-2.26012646]
Iteration 200: (w,b) = ([-3.67184831  1.29119012  1.62903917  1.51006279], [1.9517508]), cost = [-3.30094246]
Iteration 300: (w,b) = ([-3.5167961   1.43002309  1.92945208  1.75383837], [2.40553609]), cost = [-4.29816582]
Iteration 400: (w,b) = ([-3.36381537  1.56743076  2.22699739  1.99533237], [2.85469637]), cost = [-5.27534062]
Iteration 500: (w,b) = ([-3.21178236  1.70419876  2.52327401  2.23581667], [3.30179009]), cost = [-6.24363924]
Iteration 600: (w,b) = ([-3.06016794  1.84068705  2.81900167  2.47586382], [3.74798366]), cost = [-7.20808866]
Iteration 700: (w,b) = ([-2.90873526  1.97705459  3.11449429  2.71572367], [4.19378995]), cost = [-8.17088569]
Iteration 800: (w,b) = ([-2.75738087  2.11337029  3.40988677  2.95550366], [4.63943054]), cost = [-9.1329766]
Itera

<ipython-input-9-1f8d74f25a7b>:13: RuntimeWarning: divide by zero encountered in log
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)
<ipython-input-9-1f8d74f25a7b>:13: RuntimeWarning: invalid value encountered in multiply
  cost += -y[i]*np.log(f_xi) - (1-y[i])*np.log(1-f_xi)


Iteration 4100: (w,b) = ([ 2.23541551  6.61053682 13.15544862 10.86633459], [19.34159128]), cost = [nan]
Iteration 4200: (w,b) = ([ 2.38671103  6.74681371 13.45076702 11.10605541], [19.78710852]), cost = [nan]
Iteration 4300: (w,b) = ([ 2.53800655  6.88309061 13.74608542 11.34577623], [20.23262576]), cost = [nan]
Iteration 4400: (w,b) = ([ 2.68930207  7.0193675  14.04140381 11.58549706], [20.678143]), cost = [nan]
Iteration 4500: (w,b) = ([ 2.84059759  7.1556444  14.33672221 11.82521788], [21.12366025]), cost = [nan]
Iteration 4600: (w,b) = ([ 2.99189311  7.29192129 14.63204061 12.0649387 ], [21.56917749]), cost = [nan]
Iteration 4700: (w,b) = ([ 3.14318863  7.42819818 14.927359   12.30465952], [22.01469473]), cost = [nan]
Iteration 4800: (w,b) = ([ 3.29448415  7.56447508 15.2226774  12.54438034], [22.46021197]), cost = [nan]
Iteration 4900: (w,b) = ([ 3.44577967  7.70075197 15.5179958  12.78410117], [22.90572921]), cost = [nan]


(array([ 3.59556224,  7.8356661 , 15.81036101, 13.02142478]),
 array([23.34679128]),
 array([nan]))

In [13]:
print(w)

NameError: ignored